name: CI-Tests
on:
  push:
    branches:
      - "main"
      - "remote"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5

        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: "deployment"
        run: pip install pipenv && pipenv install --dev

      - name: Run Unit tests
        working-directory: "deployment"
        run: pipenv run pytest tests/

      - name: Lint
        working-directory: "deployment"
        run: pipenv run flake8 .

      - name: Integration Test
        working-directory: "deployment/integration-test"
        run: ls
